// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLS4BdpHj_-dFzWhAv9PnXlSD0-BDT64Q',
    appId: '1:250963798278:web:e1c640b4e8d9f790f91687',
    messagingSenderId: '250963798278',
    projectId: 'compass-ghibli-app',
    authDomain: 'compass-ghibli-app.firebaseapp.com',
    storageBucket: 'compass-ghibli-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoXG1H_aNjL32TmOE-iby8TZ5OJtOU8yk',
    appId: '1:250963798278:android:7968b1322c91c008f91687',
    messagingSenderId: '250963798278',
    projectId: 'compass-ghibli-app',
    storageBucket: 'compass-ghibli-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJL2Us6d83ykkfPKnFVxtVzCCtL57siD8',
    appId: '1:250963798278:ios:2a7779d1d6cfde6af91687',
    messagingSenderId: '250963798278',
    projectId: 'compass-ghibli-app',
    storageBucket: 'compass-ghibli-app.appspot.com',
    iosClientId: '250963798278-asm5urn944c761i7rqektdl17l2lggij.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghibli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJL2Us6d83ykkfPKnFVxtVzCCtL57siD8',
    appId: '1:250963798278:ios:2a7779d1d6cfde6af91687',
    messagingSenderId: '250963798278',
    projectId: 'compass-ghibli-app',
    storageBucket: 'compass-ghibli-app.appspot.com',
    iosClientId: '250963798278-asm5urn944c761i7rqektdl17l2lggij.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghibli',
  );
}
